name: Update JSON and RSS

on:
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # npm installを削除して、Node.jsパッケージなしで進める
      - name: Run getDate.js
        env:
          DYNALIST_TOKEN: ${{ secrets.DYNALIST_TOKEN }}
          DYNALIST_FILE_ID: ${{ secrets.DYNALIST_FILE_ID }}
        run: |
          set -e
          node getDate.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json rss.xml
          git commit -m "Update data.json and rss.xml"
          git push
