name: Update JSON and RSS

on:
  workflow_dispatch: # 手動トリガーのみ

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Deno
      run: |
        curl -fsSL https://deno.land/install.sh | sh
      shell: bash

    - name: Add Deno to PATH
      run: echo "${HOME}/.deno/bin" >> $GITHUB_PATH

    - name: Run getDate.js
      env:
        DYNALIST_TOKEN: ${{ secrets.DYNALIST_TOKEN }}
        DYNALIST_FILE_ID: ${{ secrets.DYNALIST_FILE_ID }}
      run: deno run --allow-net --allow-write ./getDate.js

    - name: Set GitHub user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add data.json rss.xml
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data.json and rss.xml"

    - name: Push changes
      if: success()
      run: git push
